name: release @tailor-platform/auth

on:
  push:
    branches:
      - main
    paths:
      - packages/auth/package.json

jobs:
  check-existing-release:
    uses: ./.github/workflows/check_existing_release.yml
    with:
      package_name: auth
  make-release-if-needed:
    needs: check-existing-release
    if: ${{ needs.check-existing-release.outputs.tag_exists == 'false' }}
    uses: ./.github/workflows/make_github_release.yml
    with:
      package_name: auth
      tag: ${{ needs.check-existing-release.outputs.tag }}
